services:
    nightjetter:
        image: python:3.11-alpine
        working_dir: /app
        volumes:
            - .:/app
        command: >
            sh -c "pip install --no-cache-dir -r requirements.txt && python main.py"
